collections:
  amazon.aws:
    version: 1.5.0
  ansible.netcommon:
    version: 2.2.0
  ansible.posix:
    version: 1.2.0
  ansible.utils:
    version: 2.3.0
  awx.awx:
    version: 19.2.2
  community.aws:
    version: 1.5.0
  community.docker:
    version: 1.8.0
  community.general:
    version: 3.4.0
  community.network:
    version: 3.0.0