version: '3'
services: 
    mkdocs:
        build:
            context: .
            dockerfile: ./Dockerfile
        ports: 
            - "8000:8000/tcp"
        volumes:
            - "./..:/docs"