---
- name: Tear down a workload network.
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Delete the netplan config
      ansible.builtin.file:
        path: "/etc/netplan/99-ansible-workload-network-{{ netplan_interfaces | join('-') }}.yaml"
        state: absent

    - name: Generate netplan config
      command: netplan generate

    - name: Apply the netplan config
      command: netplan apply

    - name: Flush IP addresses.
      command: ip addr flush {{ item }}
      loop: "{{ netplan_interfaces }}"
...
