---
- name: Tear down a workload network.
  hosts: all
  become: yes
  gather_facts: no
  remote_user: expeca
  vars:
    netplan_file: 99-ansible-workload-network.yaml
  tasks:
    - name: Delete the netplan config
      ansible.builtin.file:
        path: "/etc/netplan/{{netplan_file}}"
        state: absent

    - name: Apply the netplan config
      command: netplan apply
...
