---
- name: Set up a workload network
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Write netplan config
      ansible.builtin.copy:
        dest: "/etc/netplan/99-ansible-workload-network-{{ interfaces | join('-') }}.yaml"
        content: "{{ netplan_cfg }}"
        mode: 0644

    - name: Generate netplan config
      command: netplan generate

    - name: Apply the netplan config
      command: netplan apply
...
