---
- hosts: all
  become: yes
  gather_facts: no
  vars:
  tasks:
    - name: Start UE
      command: sh -c "{ cd /home/wlab/oai-all-in-docker/lte-ue && docker-compose up -d prod-oai-lte-ue; }"

    - name: Wait until UE connects
      command: ip --brief address show oaitun_ue1
      retries: 10
      delay: 3
      register: result
      until: result.stdout.split()[2] is defined

      #result.stdout.split()[0] interface name
      #result.stdout.split()[1] operstate
      #result.stdout.split()[2] ip
      #result.stdout.split()[3] mac addr

      #- name: cellular IP address
      #debug: msg="{{ result.stdout.split()[2] }}"

    - name: Save IP address
      set_fact:
        ip_address: "{{ result.stdout.split()[2] }}"
        cacheable: yes

    - name: Configure UE primary routing
      command: ip route add 192.168.61.192/26 via 12.1.1.1 dev oaitun_ue1
