---
- name: Tear down VPNCloud
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Tear down VPNCloud connection
      ansible.builtin.systemd:
        name: "vpncloud@{{ vpn_net_name }}"
        state: stopped

    - name: Delete VPNCloud config file
      ansible.builtin.file:
        path: "/etc/vpncloud/{{ vpn_net_name }}.net"
        state: absent