---
- name: Bring up VPNCloud
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Write VPNCloud config file
      ansible.builtin.copy:
        dest: "/etc/vpncloud/{{ vpn_net_name }}.net"
        # language=YAML
        content:
          listen: "{{ vpn_port }}"
          peers: "{{ vpn_peers }}"
          crypto:
            password: "{{ vpn_psk }}"
          ip: "{{ vpn_ip }}"
          ifup: "ip route add {{ vpn_gw_local_net }} via {{ vpn_gw_ip }}"
          ifdown: "ip route delete {{ vpn_gw_local_net }} via {{ vpn_gw_ip }}"
        mode: 0644

    - name: Bring up VPNCloud connection
      ansible.builtin.systemd:
        name: "vpncloud@{{ vpn_net_name }}"
        state: restarted