---
- name: Tear down VPNCloud
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Tear down VPNCloud connection
      ansible.builtin.systemd:
        name: "vpncloud@{{ item.key }}"
        state: stopped
      loop: "{{ vpn_configs | dict2items }}"

    - name: Delete VPNCloud config file
      ansible.builtin.file:
        path: "/etc/vpncloud/{{ item.key }}.net"
        state: absent
      loop: "{{ vpn_configs | dict2items }}"