#!/usr/bin/env bash

#
# Copyright (c) 2022 KTH Royal Institute of Technology, Sweden,
# and the ExPECA Research Group (PI: Prof. James Gross).
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

function get_mac_address() {
    ssh -o PubKeyAuthentication=yes -o StrictHostKeyChecking=no "$1" cat /sys/class/net/"$2"/address
}

for i in {00..10}; do
  host="workload-client-$i"
  addr=$(get_mac_address "$host" "eth0")
  printf "%s %s\n" "$host" "$addr"
done
