#!/usr/bin/env bash

function get_mac_address() {
    ssh -o PubKeyAuthentication=yes -o StrictHostKeyChecking=no "$1" cat /sys/class/net/"$2"/address
}

for i in {00..10}; do
  host="workload-client-$i"
  addr=$(get_mac_address "$host" "eth0")
  printf "%s %s" host addr
done